/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AppControllerExampleCustomSuccess200Response } from '../models';
// @ts-ignore
import type { AppControllerExampleError200Response } from '../models';
// @ts-ignore
import type { AppControllerExampleProcessing200Response } from '../models';
// @ts-ignore
import type { AppControllerExampleSuccess200Response } from '../models';
/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 示例：自定义成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleCustomSuccess: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/example/custom-success`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 示例：错误响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleError: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/example/error`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 示例：抛出自定义业务异常
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleException: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/example/exception`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 示例：任务处理中（自定义业务状态码）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleProcessing: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/example/processing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 示例：成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleSuccess: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/example/success`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 示例：自定义成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<AppControllerExampleCustomSuccess200Response>> 强制改变后期优化
         */
        async appControllerExampleCustomSuccess(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AppControllerExampleCustomSuccess200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerExampleCustomSuccess(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerExampleCustomSuccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 示例：错误响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<AppControllerExampleError200Response>> 强制改变后期优化
         */
        async appControllerExampleError(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AppControllerExampleError200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerExampleError(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerExampleError']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 示例：抛出自定义业务异常
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<AppControllerExampleProcessing200Response>> 强制改变后期优化
         */
        async appControllerExampleException(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AppControllerExampleProcessing200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerExampleException(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerExampleException']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 示例：任务处理中（自定义业务状态码）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<AppControllerExampleProcessing200Response>> 强制改变后期优化
         */
        async appControllerExampleProcessing(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AppControllerExampleProcessing200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerExampleProcessing(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerExampleProcessing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 示例：成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<AppControllerExampleSuccess200Response>> 强制改变后期优化
         */
        async appControllerExampleSuccess(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AppControllerExampleSuccess200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerExampleSuccess(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerExampleSuccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @summary 示例：自定义成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleCustomSuccess(options?: RawAxiosRequestConfig): AxiosPromise<AppControllerExampleCustomSuccess200Response> {
            return localVarFp.appControllerExampleCustomSuccess(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 示例：错误响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleError(options?: RawAxiosRequestConfig): AxiosPromise<AppControllerExampleError200Response> {
            return localVarFp.appControllerExampleError(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 示例：抛出自定义业务异常
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleException(options?: RawAxiosRequestConfig): AxiosPromise<AppControllerExampleProcessing200Response> {
            return localVarFp.appControllerExampleException(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 示例：任务处理中（自定义业务状态码）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleProcessing(options?: RawAxiosRequestConfig): AxiosPromise<AppControllerExampleProcessing200Response> {
            return localVarFp.appControllerExampleProcessing(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 示例：成功响应
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerExampleSuccess(options?: RawAxiosRequestConfig): AxiosPromise<AppControllerExampleSuccess200Response> {
            return localVarFp.appControllerExampleSuccess(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApiSdk extends BaseAPI {
    /**
     * 
     * @summary 示例：自定义成功响应
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerExampleCustomSuccess(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerExampleCustomSuccess(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 示例：错误响应
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerExampleError(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerExampleError(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 示例：抛出自定义业务异常
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerExampleException(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerExampleException(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 示例：任务处理中（自定义业务状态码）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerExampleProcessing(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerExampleProcessing(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 示例：成功响应
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerExampleSuccess(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerExampleSuccess(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 健康检查
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}

