/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AsrDto } from '../models';
/**
 * AsrApi - axios parameter creator
 * @export
 */
export const AsrApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取机器字幕
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerGetCaption: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('asrControllerGetCaption', 'id', id)
            const localVarPath = `/api/asr/caption/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取远程转录结果(用于测试)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerGetResult: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('asrControllerGetResult', 'id', id)
            const localVarPath = `/api/asr/transcribe/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AsrDto} asrDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerTranscribe: async (asrDto: AsrDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asrDto' is not null or undefined
            assertParamExists('asrControllerTranscribe', 'asrDto', asrDto)
            const localVarPath = `/api/asr/transcribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asrDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AsrApi - functional programming interface
 * @export
 */
export const AsrApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AsrApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 获取机器字幕
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async asrControllerGetCaption(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrControllerGetCaption(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsrApi.asrControllerGetCaption']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取远程转录结果(用于测试)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async asrControllerGetResult(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrControllerGetResult(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsrApi.asrControllerGetResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {AsrDto} asrDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async asrControllerTranscribe(asrDto: AsrDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrControllerTranscribe(asrDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsrApi.asrControllerTranscribe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AsrApi - factory interface
 * @export
 */
export const AsrApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AsrApiFp(configuration)
    return {
        /**
         * 
         * @summary 获取机器字幕
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerGetCaption(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.asrControllerGetCaption(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取远程转录结果(用于测试)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerGetResult(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.asrControllerGetResult(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AsrDto} asrDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrControllerTranscribe(asrDto: AsrDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.asrControllerTranscribe(asrDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AsrApi - object-oriented interface
 * @export
 * @class AsrApi
 * @extends {BaseAPI}
 */
export class AsrApiSdk extends BaseAPI {
    /**
     * 
     * @summary 获取机器字幕
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AsrApi
     */
    public asrControllerGetCaption(id: string, options?: RawAxiosRequestConfig) {
        return AsrApiFp(this.configuration).asrControllerGetCaption(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取远程转录结果(用于测试)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AsrApi
     */
    public asrControllerGetResult(id: string, options?: RawAxiosRequestConfig) {
        return AsrApiFp(this.configuration).asrControllerGetResult(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AsrDto} asrDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AsrApi
     */
    public asrControllerTranscribe(asrDto: AsrDto, options?: RawAxiosRequestConfig) {
        return AsrApiFp(this.configuration).asrControllerTranscribe(asrDto, options).then((request) => request(this.axios, this.basePath));
    }
}

