/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CacheCleanupControllerCleanupByFilePathRequest } from '../models';
/**
 * CacheCleanupApi - axios parameter creator
 * @export
 */
export const CacheCleanupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 清理指定路径的缓存文件
         * @summary 根据文件路径清理指定缓存
         * @param {CacheCleanupControllerCleanupByFilePathRequest} cacheCleanupControllerCleanupByFilePathRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerCleanupByFilePath: async (cacheCleanupControllerCleanupByFilePathRequest: CacheCleanupControllerCleanupByFilePathRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cacheCleanupControllerCleanupByFilePathRequest' is not null or undefined
            assertParamExists('cacheCleanupControllerCleanupByFilePath', 'cacheCleanupControllerCleanupByFilePathRequest', cacheCleanupControllerCleanupByFilePathRequest)
            const localVarPath = `/api/cache-cleanup/filepath`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cacheCleanupControllerCleanupByFilePathRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 查看缓存文件的统计信息
         * @summary 获取缓存状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerGetCacheStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/cache-cleanup/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 清理所有过期的缓存文件
         * @summary 手动触发缓存清理
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerManualCleanup: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/cache-cleanup/manual`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CacheCleanupApi - functional programming interface
 * @export
 */
export const CacheCleanupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CacheCleanupApiAxiosParamCreator(configuration)
    return {
        /**
         * 清理指定路径的缓存文件
         * @summary 根据文件路径清理指定缓存
         * @param {CacheCleanupControllerCleanupByFilePathRequest} cacheCleanupControllerCleanupByFilePathRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest: CacheCleanupControllerCleanupByFilePathRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheCleanupApi.cacheCleanupControllerCleanupByFilePath']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 查看缓存文件的统计信息
         * @summary 获取缓存状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async cacheCleanupControllerGetCacheStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cacheCleanupControllerGetCacheStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheCleanupApi.cacheCleanupControllerGetCacheStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 清理所有过期的缓存文件
         * @summary 手动触发缓存清理
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async cacheCleanupControllerManualCleanup(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cacheCleanupControllerManualCleanup(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheCleanupApi.cacheCleanupControllerManualCleanup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CacheCleanupApi - factory interface
 * @export
 */
export const CacheCleanupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CacheCleanupApiFp(configuration)
    return {
        /**
         * 清理指定路径的缓存文件
         * @summary 根据文件路径清理指定缓存
         * @param {CacheCleanupControllerCleanupByFilePathRequest} cacheCleanupControllerCleanupByFilePathRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest: CacheCleanupControllerCleanupByFilePathRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 查看缓存文件的统计信息
         * @summary 获取缓存状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerGetCacheStatus(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cacheCleanupControllerGetCacheStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 清理所有过期的缓存文件
         * @summary 手动触发缓存清理
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cacheCleanupControllerManualCleanup(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cacheCleanupControllerManualCleanup(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CacheCleanupApi - object-oriented interface
 * @export
 * @class CacheCleanupApi
 * @extends {BaseAPI}
 */
export class CacheCleanupApiSdk extends BaseAPI {
    /**
     * 清理指定路径的缓存文件
     * @summary 根据文件路径清理指定缓存
     * @param {CacheCleanupControllerCleanupByFilePathRequest} cacheCleanupControllerCleanupByFilePathRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheCleanupApi
     */
    public cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest: CacheCleanupControllerCleanupByFilePathRequest, options?: RawAxiosRequestConfig) {
        return CacheCleanupApiFp(this.configuration).cacheCleanupControllerCleanupByFilePath(cacheCleanupControllerCleanupByFilePathRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 查看缓存文件的统计信息
     * @summary 获取缓存状态
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheCleanupApi
     */
    public cacheCleanupControllerGetCacheStatus(options?: RawAxiosRequestConfig) {
        return CacheCleanupApiFp(this.configuration).cacheCleanupControllerGetCacheStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 清理所有过期的缓存文件
     * @summary 手动触发缓存清理
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheCleanupApi
     */
    public cacheCleanupControllerManualCleanup(options?: RawAxiosRequestConfig) {
        return CacheCleanupApiFp(this.configuration).cacheCleanupControllerManualCleanup(options).then((request) => request(this.axios, this.basePath));
    }
}

