/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * StorageR2Api - axios parameter creator
 * @export
 */
export const StorageR2ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 清理未完成的分片，回收 uploadId。
         * @summary 取消分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerAbort: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('r2MultipartControllerAbort', 'body', body)
            const localVarPath = `/api/r2-multipart/abort`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 通知 R2 合并所有分片并生成最终对象。
         * @summary 完成分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerComplete: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('r2MultipartControllerComplete', 'body', body)
            const localVarPath = `/api/r2-multipart/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 生成 Cloudflare R2 分片上传的 uploadId 与初始 key，兼容原 Next API。
         * @summary 创建分片上传会话
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerCreate: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('r2MultipartControllerCreate', 'body', body)
            const localVarPath = `/api/r2-multipart/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于客户端上传单个 part 的 PUT 签名。
         * @summary 获取分片预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerPresignPart: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('r2MultipartControllerPresignPart', 'body', body)
            const localVarPath = `/api/r2-multipart/presign-part`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 生成用于直传到 Cloudflare R2 的单文件 PUT 预签名链接，保持与 Next API 兼容
         * @summary 创建对象直传预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2UploadControllerCreateUploadUrl: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('r2UploadControllerCreateUploadUrl', 'body', body)
            const localVarPath = `/api/r2-upload-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 生成用于访问 R2 存储对象的预签名 GET 链接
         * @summary 获取 R2 对象预签名 URL
         * @param {string} key 存储对象的完整路径（Key）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2UploadControllerGetSignedUrl: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('r2UploadControllerGetSignedUrl', 'key', key)
            const localVarPath = `/api/r2-upload-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StorageR2Api - functional programming interface
 * @export
 */
export const StorageR2ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StorageR2ApiAxiosParamCreator(configuration)
    return {
        /**
         * 清理未完成的分片，回收 uploadId。
         * @summary 取消分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2MultipartControllerAbort(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2MultipartControllerAbort(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2MultipartControllerAbort']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 通知 R2 合并所有分片并生成最终对象。
         * @summary 完成分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2MultipartControllerComplete(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2MultipartControllerComplete(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2MultipartControllerComplete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 生成 Cloudflare R2 分片上传的 uploadId 与初始 key，兼容原 Next API。
         * @summary 创建分片上传会话
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2MultipartControllerCreate(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2MultipartControllerCreate(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2MultipartControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于客户端上传单个 part 的 PUT 签名。
         * @summary 获取分片预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2MultipartControllerPresignPart(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2MultipartControllerPresignPart(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2MultipartControllerPresignPart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 生成用于直传到 Cloudflare R2 的单文件 PUT 预签名链接，保持与 Next API 兼容
         * @summary 创建对象直传预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2UploadControllerCreateUploadUrl(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2UploadControllerCreateUploadUrl(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2UploadControllerCreateUploadUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 生成用于访问 R2 存储对象的预签名 GET 链接
         * @summary 获取 R2 对象预签名 URL
         * @param {string} key 存储对象的完整路径（Key）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<any>> 强制改变后期优化
         */
        async r2UploadControllerGetSignedUrl(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => any> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.r2UploadControllerGetSignedUrl(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageR2Api.r2UploadControllerGetSignedUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StorageR2Api - factory interface
 * @export
 */
export const StorageR2ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StorageR2ApiFp(configuration)
    return {
        /**
         * 清理未完成的分片，回收 uploadId。
         * @summary 取消分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerAbort(body: object, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2MultipartControllerAbort(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 通知 R2 合并所有分片并生成最终对象。
         * @summary 完成分片上传
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerComplete(body: object, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2MultipartControllerComplete(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 生成 Cloudflare R2 分片上传的 uploadId 与初始 key，兼容原 Next API。
         * @summary 创建分片上传会话
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerCreate(body: object, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2MultipartControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于客户端上传单个 part 的 PUT 签名。
         * @summary 获取分片预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2MultipartControllerPresignPart(body: object, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2MultipartControllerPresignPart(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 生成用于直传到 Cloudflare R2 的单文件 PUT 预签名链接，保持与 Next API 兼容
         * @summary 创建对象直传预签名 URL
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2UploadControllerCreateUploadUrl(body: object, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2UploadControllerCreateUploadUrl(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 生成用于访问 R2 存储对象的预签名 GET 链接
         * @summary 获取 R2 对象预签名 URL
         * @param {string} key 存储对象的完整路径（Key）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        r2UploadControllerGetSignedUrl(key: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.r2UploadControllerGetSignedUrl(key, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StorageR2Api - object-oriented interface
 * @export
 * @class StorageR2Api
 * @extends {BaseAPI}
 */
export class StorageR2ApiSdk extends BaseAPI {
    /**
     * 清理未完成的分片，回收 uploadId。
     * @summary 取消分片上传
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2MultipartControllerAbort(body: object, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2MultipartControllerAbort(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 通知 R2 合并所有分片并生成最终对象。
     * @summary 完成分片上传
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2MultipartControllerComplete(body: object, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2MultipartControllerComplete(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 生成 Cloudflare R2 分片上传的 uploadId 与初始 key，兼容原 Next API。
     * @summary 创建分片上传会话
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2MultipartControllerCreate(body: object, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2MultipartControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于客户端上传单个 part 的 PUT 签名。
     * @summary 获取分片预签名 URL
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2MultipartControllerPresignPart(body: object, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2MultipartControllerPresignPart(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 生成用于直传到 Cloudflare R2 的单文件 PUT 预签名链接，保持与 Next API 兼容
     * @summary 创建对象直传预签名 URL
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2UploadControllerCreateUploadUrl(body: object, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2UploadControllerCreateUploadUrl(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 生成用于访问 R2 存储对象的预签名 GET 链接
     * @summary 获取 R2 对象预签名 URL
     * @param {string} key 存储对象的完整路径（Key）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageR2Api
     */
    public r2UploadControllerGetSignedUrl(key: string, options?: RawAxiosRequestConfig) {
        return StorageR2ApiFp(this.configuration).r2UploadControllerGetSignedUrl(key, options).then((request) => request(this.axios, this.basePath));
    }
}

