/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SubtitleAiCommonDto } from '../models';
// @ts-ignore
import type { SubtitleAiControllerOutline200Response } from '../models';
// @ts-ignore
import type { SubtitleAiControllerSpeech200Response } from '../models';
// @ts-ignore
import type { SubtitleAiControllerSummary200Response } from '../models';
// @ts-ignore
import type { SubtitleAiControllerTranslate200Response } from '../models';
// @ts-ignore
import type { SubtitleAiTranslationDto } from '../models';
/**
 * SubtitleAiApi - axios parameter creator
 * @export
 */
export const SubtitleAiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary AI 大纲（生成目录）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerOutline: async (subtitleAiCommonDto: SubtitleAiCommonDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subtitleAiCommonDto' is not null or undefined
            assertParamExists('subtitleAiControllerOutline', 'subtitleAiCommonDto', subtitleAiCommonDto)
            const localVarPath = `/api/subtitle/ai/outline`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subtitleAiCommonDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary AI 演讲稿（生成演讲稿）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerSpeech: async (subtitleAiCommonDto: SubtitleAiCommonDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subtitleAiCommonDto' is not null or undefined
            assertParamExists('subtitleAiControllerSpeech', 'subtitleAiCommonDto', subtitleAiCommonDto)
            const localVarPath = `/api/subtitle/ai/speech`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subtitleAiCommonDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary AI 摘要（生成段落总结 / key points）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerSummary: async (subtitleAiCommonDto: SubtitleAiCommonDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subtitleAiCommonDto' is not null or undefined
            assertParamExists('subtitleAiControllerSummary', 'subtitleAiCommonDto', subtitleAiCommonDto)
            const localVarPath = `/api/subtitle/ai/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subtitleAiCommonDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary AI 翻译（生成翻译字幕）
         * @param {SubtitleAiTranslationDto} subtitleAiTranslationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerTranslate: async (subtitleAiTranslationDto: SubtitleAiTranslationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subtitleAiTranslationDto' is not null or undefined
            assertParamExists('subtitleAiControllerTranslate', 'subtitleAiTranslationDto', subtitleAiTranslationDto)
            const localVarPath = `/api/subtitle/ai/translate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subtitleAiTranslationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubtitleAiApi - functional programming interface
 * @export
 */
export const SubtitleAiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubtitleAiApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary AI 大纲（生成目录）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleAiControllerOutline200Response>> 强制改变后期优化
         */
        async subtitleAiControllerOutline(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleAiControllerOutline200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleAiControllerOutline(subtitleAiCommonDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleAiApi.subtitleAiControllerOutline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary AI 演讲稿（生成演讲稿）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleAiControllerSpeech200Response>> 强制改变后期优化
         */
        async subtitleAiControllerSpeech(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleAiControllerSpeech200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleAiControllerSpeech(subtitleAiCommonDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleAiApi.subtitleAiControllerSpeech']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary AI 摘要（生成段落总结 / key points）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleAiControllerSummary200Response>> 强制改变后期优化
         */
        async subtitleAiControllerSummary(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleAiControllerSummary200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleAiControllerSummary(subtitleAiCommonDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleAiApi.subtitleAiControllerSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary AI 翻译（生成翻译字幕）
         * @param {SubtitleAiTranslationDto} subtitleAiTranslationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleAiControllerTranslate200Response>> 强制改变后期优化
         */
        async subtitleAiControllerTranslate(subtitleAiTranslationDto: SubtitleAiTranslationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleAiControllerTranslate200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleAiControllerTranslate(subtitleAiTranslationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleAiApi.subtitleAiControllerTranslate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubtitleAiApi - factory interface
 * @export
 */
export const SubtitleAiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubtitleAiApiFp(configuration)
    return {
        /**
         * 
         * @summary AI 大纲（生成目录）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerOutline(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleAiControllerOutline200Response> {
            return localVarFp.subtitleAiControllerOutline(subtitleAiCommonDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary AI 演讲稿（生成演讲稿）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerSpeech(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleAiControllerSpeech200Response> {
            return localVarFp.subtitleAiControllerSpeech(subtitleAiCommonDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary AI 摘要（生成段落总结 / key points）
         * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerSummary(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleAiControllerSummary200Response> {
            return localVarFp.subtitleAiControllerSummary(subtitleAiCommonDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary AI 翻译（生成翻译字幕）
         * @param {SubtitleAiTranslationDto} subtitleAiTranslationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleAiControllerTranslate(subtitleAiTranslationDto: SubtitleAiTranslationDto, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleAiControllerTranslate200Response> {
            return localVarFp.subtitleAiControllerTranslate(subtitleAiTranslationDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubtitleAiApi - object-oriented interface
 * @export
 * @class SubtitleAiApi
 * @extends {BaseAPI}
 */
export class SubtitleAiApiSdk extends BaseAPI {
    /**
     * 
     * @summary AI 大纲（生成目录）
     * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleAiApi
     */
    public subtitleAiControllerOutline(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig) {
        return SubtitleAiApiFp(this.configuration).subtitleAiControllerOutline(subtitleAiCommonDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary AI 演讲稿（生成演讲稿）
     * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleAiApi
     */
    public subtitleAiControllerSpeech(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig) {
        return SubtitleAiApiFp(this.configuration).subtitleAiControllerSpeech(subtitleAiCommonDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary AI 摘要（生成段落总结 / key points）
     * @param {SubtitleAiCommonDto} subtitleAiCommonDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleAiApi
     */
    public subtitleAiControllerSummary(subtitleAiCommonDto: SubtitleAiCommonDto, options?: RawAxiosRequestConfig) {
        return SubtitleAiApiFp(this.configuration).subtitleAiControllerSummary(subtitleAiCommonDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary AI 翻译（生成翻译字幕）
     * @param {SubtitleAiTranslationDto} subtitleAiTranslationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleAiApi
     */
    public subtitleAiControllerTranslate(subtitleAiTranslationDto: SubtitleAiTranslationDto, options?: RawAxiosRequestConfig) {
        return SubtitleAiApiFp(this.configuration).subtitleAiControllerTranslate(subtitleAiTranslationDto, options).then((request) => request(this.axios, this.basePath));
    }
}

