/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SubtitleEmbedControllerEmbed200Response } from '../models';
// @ts-ignore
import type { SubtitleEmbedControllerGetTask200Response } from '../models';
// @ts-ignore
import type { SubtitleEmbedControllerPutSubtitle200Response } from '../models';
// @ts-ignore
import type { UpdateSubtitleDto } from '../models';
/**
 * SubtitleApi - axios parameter creator
 * @export
 */
export const SubtitleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建字幕嵌入视频任务
         * @param {string} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerEmbed: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('subtitleEmbedControllerEmbed', 'id', id)
            const localVarPath = `/api/subtitle/export-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据任务 ID 导出 SRT 或 VTT 格式的字幕文件
         * @summary 导出字幕文件
         * @param {string} id 转录任务 ID
         * @param {SubtitleEmbedControllerExportSubtitleFileTypeEnum} type 字幕文件类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerExportSubtitleFile: async (id: string, type: SubtitleEmbedControllerExportSubtitleFileTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('subtitleEmbedControllerExportSubtitleFile', 'id', id)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('subtitleEmbedControllerExportSubtitleFile', 'type', type)
            const localVarPath = `/api/subtitle/export-file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取指定任务id的导出字幕结果
         * @param {number} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerGetTask: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('subtitleEmbedControllerGetTask', 'id', id)
            const localVarPath = `/api/subtitle/subtitle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 通过任务 ID 更新字幕 JSON 数据，支持空数组 []
         * @summary 更新字幕内容
         * @param {UpdateSubtitleDto} updateSubtitleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerPutSubtitle: async (updateSubtitleDto: UpdateSubtitleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateSubtitleDto' is not null or undefined
            assertParamExists('subtitleEmbedControllerPutSubtitle', 'updateSubtitleDto', updateSubtitleDto)
            const localVarPath = `/api/subtitle/subtitle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSubtitleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubtitleApi - functional programming interface
 * @export
 */
export const SubtitleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubtitleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建字幕嵌入视频任务
         * @param {string} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleEmbedControllerEmbed200Response>> 强制改变后期优化
         */
        async subtitleEmbedControllerEmbed(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleEmbedControllerEmbed200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleEmbedControllerEmbed(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleApi.subtitleEmbedControllerEmbed']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 根据任务 ID 导出 SRT 或 VTT 格式的字幕文件
         * @summary 导出字幕文件
         * @param {string} id 转录任务 ID
         * @param {SubtitleEmbedControllerExportSubtitleFileTypeEnum} type 字幕文件类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<void>> 强制改变后期优化
         */
        async subtitleEmbedControllerExportSubtitleFile(id: string, type: SubtitleEmbedControllerExportSubtitleFileTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => void> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleEmbedControllerExportSubtitleFile(id, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleApi.subtitleEmbedControllerExportSubtitleFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取指定任务id的导出字幕结果
         * @param {number} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleEmbedControllerGetTask200Response>> 强制改变后期优化
         */
        async subtitleEmbedControllerGetTask(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleEmbedControllerGetTask200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleEmbedControllerGetTask(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleApi.subtitleEmbedControllerGetTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 通过任务 ID 更新字幕 JSON 数据，支持空数组 []
         * @summary 更新字幕内容
         * @param {UpdateSubtitleDto} updateSubtitleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<SubtitleEmbedControllerPutSubtitle200Response>> 强制改变后期优化
         */
        async subtitleEmbedControllerPutSubtitle(updateSubtitleDto: UpdateSubtitleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => SubtitleEmbedControllerPutSubtitle200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subtitleEmbedControllerPutSubtitle(updateSubtitleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubtitleApi.subtitleEmbedControllerPutSubtitle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubtitleApi - factory interface
 * @export
 */
export const SubtitleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubtitleApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建字幕嵌入视频任务
         * @param {string} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerEmbed(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleEmbedControllerEmbed200Response> {
            return localVarFp.subtitleEmbedControllerEmbed(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据任务 ID 导出 SRT 或 VTT 格式的字幕文件
         * @summary 导出字幕文件
         * @param {string} id 转录任务 ID
         * @param {SubtitleEmbedControllerExportSubtitleFileTypeEnum} type 字幕文件类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerExportSubtitleFile(id: string, type: SubtitleEmbedControllerExportSubtitleFileTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.subtitleEmbedControllerExportSubtitleFile(id, type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取指定任务id的导出字幕结果
         * @param {number} id 字幕导出任务 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerGetTask(id: number, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleEmbedControllerGetTask200Response> {
            return localVarFp.subtitleEmbedControllerGetTask(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 通过任务 ID 更新字幕 JSON 数据，支持空数组 []
         * @summary 更新字幕内容
         * @param {UpdateSubtitleDto} updateSubtitleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subtitleEmbedControllerPutSubtitle(updateSubtitleDto: UpdateSubtitleDto, options?: RawAxiosRequestConfig): AxiosPromise<SubtitleEmbedControllerPutSubtitle200Response> {
            return localVarFp.subtitleEmbedControllerPutSubtitle(updateSubtitleDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubtitleApi - object-oriented interface
 * @export
 * @class SubtitleApi
 * @extends {BaseAPI}
 */
export class SubtitleApiSdk extends BaseAPI {
    /**
     * 
     * @summary 创建字幕嵌入视频任务
     * @param {string} id 字幕导出任务 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleApi
     */
    public subtitleEmbedControllerEmbed(id: string, options?: RawAxiosRequestConfig) {
        return SubtitleApiFp(this.configuration).subtitleEmbedControllerEmbed(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据任务 ID 导出 SRT 或 VTT 格式的字幕文件
     * @summary 导出字幕文件
     * @param {string} id 转录任务 ID
     * @param {SubtitleEmbedControllerExportSubtitleFileTypeEnum} type 字幕文件类型
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleApi
     */
    public subtitleEmbedControllerExportSubtitleFile(id: string, type: SubtitleEmbedControllerExportSubtitleFileTypeEnum, options?: RawAxiosRequestConfig) {
        return SubtitleApiFp(this.configuration).subtitleEmbedControllerExportSubtitleFile(id, type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取指定任务id的导出字幕结果
     * @param {number} id 字幕导出任务 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleApi
     */
    public subtitleEmbedControllerGetTask(id: number, options?: RawAxiosRequestConfig) {
        return SubtitleApiFp(this.configuration).subtitleEmbedControllerGetTask(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 通过任务 ID 更新字幕 JSON 数据，支持空数组 []
     * @summary 更新字幕内容
     * @param {UpdateSubtitleDto} updateSubtitleDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubtitleApi
     */
    public subtitleEmbedControllerPutSubtitle(updateSubtitleDto: UpdateSubtitleDto, options?: RawAxiosRequestConfig) {
        return SubtitleApiFp(this.configuration).subtitleEmbedControllerPutSubtitle(updateSubtitleDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const SubtitleEmbedControllerExportSubtitleFileTypeEnum = {
    Srt: 'srt',
    Vtt: 'vtt'
} as const;
export type SubtitleEmbedControllerExportSubtitleFileTypeEnum = typeof SubtitleEmbedControllerExportSubtitleFileTypeEnum[keyof typeof SubtitleEmbedControllerExportSubtitleFileTypeEnum];
