/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'src/lib/http';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EmailLoginDto } from '../models';
// @ts-ignore
import type { GoogleLoginDto } from '../models';
// @ts-ignore
import type { RefreshTokenDto } from '../models';
// @ts-ignore
import type { SendVerificationCodeDto } from '../models';
// @ts-ignore
import type { UserControllerEmailLoginDefaultResponse } from '../models';
// @ts-ignore
import type { UserControllerGetCurrentUser200Response } from '../models';
// @ts-ignore
import type { UserControllerLogout200Response } from '../models';
// @ts-ignore
import type { UserControllerRefreshToken200Response } from '../models';
// @ts-ignore
import type { UserControllerSendVerificationCode200Response } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 邮箱验证码登录（新用户自动注册）
         * @param {EmailLoginDto} emailLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerEmailLogin: async (emailLoginDto: EmailLoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailLoginDto' is not null or undefined
            assertParamExists('userControllerEmailLogin', 'emailLoginDto', emailLoginDto)
            const localVarPath = `/api/user/email-login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailLoginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取当前用户信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Google 登录（新用户自动注册）
         * @param {GoogleLoginDto} googleLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGoogleLogin: async (googleLoginDto: GoogleLoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'googleLoginDto' is not null or undefined
            assertParamExists('userControllerGoogleLogin', 'googleLoginDto', googleLoginDto)
            const localVarPath = `/api/user/google-login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(googleLoginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 登出
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLogout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 刷新访问令牌
         * @param {RefreshTokenDto} refreshTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerRefreshToken: async (refreshTokenDto: RefreshTokenDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshTokenDto' is not null or undefined
            assertParamExists('userControllerRefreshToken', 'refreshTokenDto', refreshTokenDto)
            const localVarPath = `/api/user/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshTokenDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 发送登录验证码
         * @param {SendVerificationCodeDto} sendVerificationCodeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerSendVerificationCode: async (sendVerificationCodeDto: SendVerificationCodeDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendVerificationCodeDto' is not null or undefined
            assertParamExists('userControllerSendVerificationCode', 'sendVerificationCodeDto', sendVerificationCodeDto)
            const localVarPath = `/api/user/send-verification-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendVerificationCodeDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 邮箱验证码登录（新用户自动注册）
         * @param {EmailLoginDto} emailLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerEmailLoginDefaultResponse>> 强制改变后期优化
         */
        async userControllerEmailLogin(emailLoginDto: EmailLoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerEmailLoginDefaultResponse> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerEmailLogin(emailLoginDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerEmailLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取当前用户信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerGetCurrentUser200Response>> 强制改变后期优化
         */
        async userControllerGetCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerGetCurrentUser200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerGetCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Google 登录（新用户自动注册）
         * @param {GoogleLoginDto} googleLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerEmailLoginDefaultResponse>> 强制改变后期优化
         */
        async userControllerGoogleLogin(googleLoginDto: GoogleLoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerEmailLoginDefaultResponse> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGoogleLogin(googleLoginDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerGoogleLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 登出
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerLogout200Response>> 强制改变后期优化
         */
        async userControllerLogout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerLogout200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerLogout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerLogout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 刷新访问令牌
         * @param {RefreshTokenDto} refreshTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerRefreshToken200Response>> 强制改变后期优化
         */
        async userControllerRefreshToken(refreshTokenDto: RefreshTokenDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerRefreshToken200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerRefreshToken(refreshTokenDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerRefreshToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 发送登录验证码
         * @param {SendVerificationCodeDto} sendVerificationCodeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * TODO AxiosPromise<UserControllerSendVerificationCode200Response>> 强制改变后期优化
         */
        async userControllerSendVerificationCode(sendVerificationCodeDto: SendVerificationCodeDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => UserControllerSendVerificationCode200Response> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerSendVerificationCode(sendVerificationCodeDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerSendVerificationCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary 邮箱验证码登录（新用户自动注册）
         * @param {EmailLoginDto} emailLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerEmailLogin(emailLoginDto: EmailLoginDto, options?: RawAxiosRequestConfig): AxiosPromise<UserControllerEmailLoginDefaultResponse> {
            return localVarFp.userControllerEmailLogin(emailLoginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取当前用户信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<UserControllerGetCurrentUser200Response> {
            return localVarFp.userControllerGetCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Google 登录（新用户自动注册）
         * @param {GoogleLoginDto} googleLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGoogleLogin(googleLoginDto: GoogleLoginDto, options?: RawAxiosRequestConfig): AxiosPromise<UserControllerEmailLoginDefaultResponse> {
            return localVarFp.userControllerGoogleLogin(googleLoginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 登出
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLogout(options?: RawAxiosRequestConfig): AxiosPromise<UserControllerLogout200Response> {
            return localVarFp.userControllerLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 刷新访问令牌
         * @param {RefreshTokenDto} refreshTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerRefreshToken(refreshTokenDto: RefreshTokenDto, options?: RawAxiosRequestConfig): AxiosPromise<UserControllerRefreshToken200Response> {
            return localVarFp.userControllerRefreshToken(refreshTokenDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 发送登录验证码
         * @param {SendVerificationCodeDto} sendVerificationCodeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerSendVerificationCode(sendVerificationCodeDto: SendVerificationCodeDto, options?: RawAxiosRequestConfig): AxiosPromise<UserControllerSendVerificationCode200Response> {
            return localVarFp.userControllerSendVerificationCode(sendVerificationCodeDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApiSdk extends BaseAPI {
    /**
     * 
     * @summary 邮箱验证码登录（新用户自动注册）
     * @param {EmailLoginDto} emailLoginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerEmailLogin(emailLoginDto: EmailLoginDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerEmailLogin(emailLoginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取当前用户信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerGetCurrentUser(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerGetCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Google 登录（新用户自动注册）
     * @param {GoogleLoginDto} googleLoginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerGoogleLogin(googleLoginDto: GoogleLoginDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerGoogleLogin(googleLoginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 登出
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerLogout(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 刷新访问令牌
     * @param {RefreshTokenDto} refreshTokenDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerRefreshToken(refreshTokenDto: RefreshTokenDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerRefreshToken(refreshTokenDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 发送登录验证码
     * @param {SendVerificationCodeDto} sendVerificationCodeDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerSendVerificationCode(sendVerificationCodeDto: SendVerificationCodeDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerSendVerificationCode(sendVerificationCodeDto, options).then((request) => request(this.axios, this.basePath));
    }
}

