/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppControllerExampleSuccess200ResponseData } from './app-controller-example-success200-response-data';

/**
 * 
 * @export
 * @interface AppControllerExampleSuccess200Response
 */
export interface AppControllerExampleSuccess200Response {
    /**
     * 
     * @type {number}
     * @memberof AppControllerExampleSuccess200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof AppControllerExampleSuccess200Response
     */
    'message'?: string;
    /**
     * 
     * @type {AppControllerExampleSuccess200ResponseData}
     * @memberof AppControllerExampleSuccess200Response
     */
    'data'?: AppControllerExampleSuccess200ResponseData;
}

