/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppControllerExampleError200Response
 */
export interface AppControllerExampleError200Response {
    /**
     * 
     * @type {number}
     * @memberof AppControllerExampleError200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof AppControllerExampleError200Response
     */
    'message'?: string;
    /**
     * 
     * @type {any}
     * @memberof AppControllerExampleError200Response
     */
    'data'?: any | null;
}

