/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppControllerExampleSuccess200ResponseData
 */
export interface AppControllerExampleSuccess200ResponseData {
    /**
     * 
     * @type {number}
     * @memberof AppControllerExampleSuccess200ResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AppControllerExampleSuccess200ResponseData
     */
    'name'?: string;
}

