/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AsrDto
 */
export interface AsrDto {
    /**
     * 文件名称
     * @type {string}
     * @memberof AsrDto
     */
    'fileName': string;
    /**
     * 文件大小
     * @type {number}
     * @memberof AsrDto
     */
    'fileSize': number;
    /**
     * 文件路径
     * @type {string}
     * @memberof AsrDto
     */
    'storageKey': string;
}

