/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmailLoginDto
 */
export interface EmailLoginDto {
    /**
     * 用户邮箱
     * @type {string}
     * @memberof EmailLoginDto
     */
    'email': string;
    /**
     * 验证码
     * @type {string}
     * @memberof EmailLoginDto
     */
    'code': string;
}

