/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OutlineResponseDto
 */
export interface OutlineResponseDto {
    /**
     * AI生成的大纲内容
     * @type {string}
     * @memberof OutlineResponseDto
     */
    'outline': string;
}

