/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RefreshTokenResponseDto
 */
export interface RefreshTokenResponseDto {
    /**
     * 响应消息
     * @type {string}
     * @memberof RefreshTokenResponseDto
     */
    'message': string;
    /**
     * 访问令牌
     * @type {string}
     * @memberof RefreshTokenResponseDto
     */
    'accessToken': string;
    /**
     * 刷新令牌
     * @type {string}
     * @memberof RefreshTokenResponseDto
     */
    'refreshToken': string;
}

