/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SendVerificationCodeResponseDto
 */
export interface SendVerificationCodeResponseDto {
    /**
     * 响应消息
     * @type {string}
     * @memberof SendVerificationCodeResponseDto
     */
    'message': string;
}

