/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpeechResponseDto
 */
export interface SpeechResponseDto {
    /**
     * AI生成的演讲稿内容
     * @type {string}
     * @memberof SpeechResponseDto
     */
    'speech': string;
}

