/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubtitleAiTranslationDto
 */
export interface SubtitleAiTranslationDto {
    /**
     * 字幕id
     * @type {number}
     * @memberof SubtitleAiTranslationDto
     */
    'id': number;
    /**
     * 源语言
     * @type {string}
     * @memberof SubtitleAiTranslationDto
     */
    'sourceLang': string;
    /**
     * 目标语言
     * @type {string}
     * @memberof SubtitleAiTranslationDto
     */
    'targetLang': string;
}

