/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubtitleAiCommonDto
 */
export interface SubtitleAiCommonDto {
    /**
     * 字幕id
     * @type {number}
     * @memberof SubtitleAiCommonDto
     */
    'id': number;
}

