/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SummaryResponseDto } from './summary-response-dto';

/**
 * 
 * @export
 * @interface SubtitleAiControllerSummary200Response
 */
export interface SubtitleAiControllerSummary200Response {
    /**
     * 业务状态码
     * @type {number}
     * @memberof SubtitleAiControllerSummary200Response
     */
    'code': number;
    /**
     * 响应消息
     * @type {string}
     * @memberof SubtitleAiControllerSummary200Response
     */
    'message': string;
    /**
     * 
     * @type {SummaryResponseDto}
     * @memberof SubtitleAiControllerSummary200Response
     */
    'data'?: SummaryResponseDto;
}

