/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubtitleDataResponseDto
 */
export interface SubtitleDataResponseDto {
    /**
     * 任务ID
     * @type {string}
     * @memberof SubtitleDataResponseDto
     */
    'id': string;
    /**
     * 字幕JSON数据
     * @type {Array<string>}
     * @memberof SubtitleDataResponseDto
     */
    'captionJson': Array<string>;
}

