/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskIdResponseDto
 */
export interface TaskIdResponseDto {
    /**
     * 任务ID
     * @type {string}
     * @memberof TaskIdResponseDto
     */
    'taskId': string;
    /**
     * 响应消息
     * @type {string}
     * @memberof TaskIdResponseDto
     */
    'message'?: string;
}

