/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateSubtitleDtoCaptionJsonInner } from './update-subtitle-dto-caption-json-inner';

/**
 * 
 * @export
 * @interface UpdateSubtitleDto
 */
export interface UpdateSubtitleDto {
    /**
     * 转录任务 ID
     * @type {string}
     * @memberof UpdateSubtitleDto
     */
    'id': string;
    /**
     * 字幕 JSON 数据，格式为 CaptionItem 数组
     * @type {Array<UpdateSubtitleDtoCaptionJsonInner>}
     * @memberof UpdateSubtitleDto
     */
    'captionJson': Array<UpdateSubtitleDtoCaptionJsonInner>;
}

