/* tslint:disable */
/* eslint-disable */
/**
 * Ling Workshop API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSubtitleDtoCaptionJsonInner
 */
export interface UpdateSubtitleDtoCaptionJsonInner {
    /**
     * SRT 格式开始时间
     * @type {string}
     * @memberof UpdateSubtitleDtoCaptionJsonInner
     */
    'start'?: string;
    /**
     * SRT 格式结束时间
     * @type {string}
     * @memberof UpdateSubtitleDtoCaptionJsonInner
     */
    'end'?: string;
    /**
     * 字幕文本
     * @type {string}
     * @memberof UpdateSubtitleDtoCaptionJsonInner
     */
    'text'?: string;
}

